spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.0.52.7:1521:orcl
    username: hbzz
    password: Ri0PCaBPKAIKltOrYQI4PwW9KWcF5JXcVvUPWdFzD5C6kpmEccCgJ8wwadseDQm86LmEidB5AWAzh8q1kT8CKQ==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKQtAC12Y5ptIlNtvEgAAaVz+a0y87PDDYcoEZB8Axxagt0SxRKeb/i6SsjjuUSVpPsR73uJ6J5U1ThgNALfo30CAwEAAQ==
    druid:
      async-init: true
      initial-size: 15
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validation-query: SELECT 1 FROM DUAL
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true


  redis:
      database: 0
      host: localhost
      port: 6379
      password:      # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file: /logs/logback.log
