server:
  port: 7999

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

zuul:
  routes:
    sys-service: /sys/**

# swagger配置
swagger:
  # 扫描包
  base-package: com.sofn.gatewayservice.web
  # 名称
  name: 网关
  # 接口前缀
  prefix: